insert into public.branches (id, slug, name, address, plus_code, latitude, longitude, smart_phone, globe_phone, google_review_url, is_google_business_verified)
values
  ('11111111-1111-4111-8111-111111111111', 'valley-1', 'Valley 1 Branch', '138-C Barangay San Antonio, Valley 1, Parañaque City', 'F2CC+3J Parañaque, Metro Manila', null, null, '0968 312 5797', '0915 695 6460', 'https://g.page/r/CZHke-5ErCgREBM/review', true),
  ('22222222-2222-4222-8222-222222222222', 'bf-irineville', 'BF Homes / Irineville Branch', 'Blk 4 Lot 13 Doña Irenea Ave., Irineville 1, BF Homes, Parañaque City', 'F22M+QQ5 Parañaque, Metro Manila', 14.451889, 121.034500, '0961 608 4124', '0954 438 5175', null, false)
on conflict (id) do update set name = excluded.name, address = excluded.address, plus_code = excluded.plus_code, latitude = excluded.latitude, longitude = excluded.longitude, smart_phone = excluded.smart_phone, globe_phone = excluded.globe_phone, google_review_url = excluded.google_review_url, is_google_business_verified = excluded.is_google_business_verified;

insert into public.services (id, slug, name, category, short_description, long_description, default_duration_minutes, price, is_active, is_featured)
values
  ('33333333-3333-4333-8333-000000000001', 'oral-prophylaxis', 'Oral Prophylaxis', 'Preventive / Periodontal', 'Keep your smile healthy with professional cleaning and plaque removal.', 'Oral Prophylaxis is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, true),
  ('33333333-3333-4333-8333-000000000002', 'teeth-whitening', 'Teeth Whitening', 'Preventive / Periodontal', 'A brighter, more confident smile with dentist-guided whitening.', 'Teeth Whitening is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, true),
  ('33333333-3333-4333-8333-000000000003', 'deep-scaling-root-planing', 'Deep Scaling & Root Planing', 'Preventive / Periodontal', 'Treat gum concerns with thorough deep cleaning.', 'Deep Scaling & Root Planing is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000004', 'pit-and-fissure-sealant', 'Pit and Fissure Sealant', 'Preventive / Periodontal', 'Help protect hard-to-clean grooves from decay.', 'Pit and Fissure Sealant is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000005', 'periodontal-treatment', 'Periodontal Treatment', 'Preventive / Periodontal', 'Care for your gums and supporting structures.', 'Periodontal Treatment is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000006', 'composite-restoration', 'Composite Restoration', 'Restorative / Endodontic', 'Repair cavities with natural-looking tooth-colored fillings.', 'Composite Restoration is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000007', 'pulpotomy', 'Pulpotomy', 'Restorative / Endodontic', 'A focused treatment for an affected portion of the tooth pulp.', 'Pulpotomy is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000008', 'pulpectomy', 'Pulpectomy', 'Restorative / Endodontic', 'Remove affected pulp as part of a dentist-led treatment plan.', 'Pulpectomy is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000009', 'root-canal-therapy', 'Root Canal Therapy', 'Restorative / Endodontic', 'Save your natural tooth and relieve pain from infected pulp.', 'Root canal therapy is a dentist-led treatment that removes infected or damaged pulp, cleans and disinfects the root canals, and seals the tooth to help preserve natural function.', 60, null, true, true),
  ('33333333-3333-4333-8333-000000000010', 'stainless-steel-crown', 'Stainless Steel Crown', 'Restorative / Endodontic', 'Durable crowns for children’s teeth when protection is needed.', 'Stainless Steel Crown is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000011', 'crowns-fixed-bridge', 'Crowns & Fixed Bridge', 'Restorative / Endodontic', 'Restore strength and function with high-quality crowns and bridges.', 'Crowns & Fixed Bridge is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000012', 'tooth-extraction', 'Tooth Extraction', 'Surgical / Replacement', 'Safe, thoughtful extraction when a tooth cannot be saved.', 'Tooth Extraction is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000013', 'dental-implant', 'Dental Implant', 'Surgical / Replacement', 'A long-lasting option for replacing missing teeth.', 'Dental Implant is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000014', 'dentures', 'Dentures', 'Cosmetic / Prosthodontic', 'Comfortable, natural-looking solutions for missing teeth.', 'Dentures is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000015', 'veneers', 'Veneers', 'Cosmetic / Prosthodontic', 'Enhance your smile with carefully planned veneers.', 'Veneers is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000016', 'gum-contouring', 'Gum Contouring', 'Cosmetic / Prosthodontic', 'Refine the appearance of your smile with gum contouring.', 'Gum Contouring is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000017', 'orthodontic-treatment', 'Orthodontic Treatment', 'Orthodontic', 'Straighter smiles with a dentist-guided treatment plan.', 'Orthodontic Treatment is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000018', 'retainer', 'Retainer', 'Orthodontic', 'Help maintain alignment after orthodontic treatment.', 'Retainer is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000019', 'expander', 'Expander', 'Orthodontic', 'Support jaw and dental development when clinically appropriate.', 'Expander is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000020', 'mouth-guard', 'Mouth Guard', 'Orthodontic', 'Protect teeth during sport or while managing nighttime grinding.', 'Mouth Guard is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, false),
  ('33333333-3333-4333-8333-000000000021', 'pediatric-dentistry', 'Pediatric Dentistry', 'Pediatric', 'Gentle, friendly care for children’s growing smiles.', 'Pediatric Dentistry is available as part of a personalized care plan. Your dentist will assess your needs and explain what the treatment may involve.', 60, null, true, true)
on conflict (id) do update set name = excluded.name, category = excluded.category, short_description = excluded.short_description, long_description = excluded.long_description, default_duration_minutes = excluded.default_duration_minutes, is_active = excluded.is_active, is_featured = excluded.is_featured;

insert into public.branch_services (branch_id, service_id)
select b.id, s.id from public.branches b cross join public.services s
on conflict (branch_id, service_id) do update set is_available = true;

insert into public.availability_rules (branch_id, weekday, open_time, close_time, slot_interval_minutes, capacity)
select id, weekday, '08:00', '20:00', 30, 1
from public.branches cross join generate_series(1, 6) as weekday
on conflict (branch_id, staff_id, weekday) do update set open_time = excluded.open_time, close_time = excluded.close_time, slot_interval_minutes = excluded.slot_interval_minutes, capacity = excluded.capacity, is_active = true;

insert into public.system_settings (key, value)
values
  ('business', '{"name":"M.A.B. Dental Clinic","tagline":"Your Smile is Our Masterpiece.","timezone":"Asia/Manila","consultation":"Free Consultation and Assessment"}'::jsonb),
  ('booking', '{"slot_interval_minutes":30,"capacity":1,"confirmation_mode":"request_then_confirm"}'::jsonb)
on conflict (key) do update set value = excluded.value;
