import { test, expect, type Page } from '@playwright/test'

function futureDate() {
  const date = new Date()
  date.setDate(date.getDate() + 2)
  while (date.getDay() === 0) date.setDate(date.getDate() + 1)
  return date.toISOString().slice(0, 10)
}

async function clickNext(page: Page) {
  const button = page.getByRole('button', { name: /Next step/ })
  await button.scrollIntoViewIfNeeded()
  await button.click({ force: true })
}

test('patient can request an appointment and staff can review it', async ({ page, browserName, request }) => {
  test.skip(browserName !== 'chromium', 'The end-to-end workflow is run once in Chromium.')
  await request.post('http://localhost:3001/api/test/reset', { headers: { 'x-mab-test-reset': 'local-only' } })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dental care, thoughtfully done.' })).toBeVisible()
  await page.getByRole('link', { name: /Book Appointment/ }).first().click()
  await page.waitForURL('**/book')
  await page.waitForLoadState('networkidle')
  await page.waitForTimeout(1000)
  await expect(page.getByRole('heading', { name: 'Choose a location' })).toBeVisible()
  const valleyChoice = page.getByRole('button', { name: /Valley 1 Branch/ })
  await valleyChoice.scrollIntoViewIfNeeded()
  await valleyChoice.click({ force: true })
  await page.waitForTimeout(100)
  await clickNext(page)
  await expect(page.getByText('STEP 2 OF 5')).toBeVisible()
  const cleaningChoice = page.getByRole('button', { name: /Oral Prophylaxis/ })
  await cleaningChoice.scrollIntoViewIfNeeded()
  await cleaningChoice.click({ force: true })
  await clickNext(page)
  await page.locator('input[type="date"]').fill(futureDate())
  await page.locator('select').selectOption('10:00')
  await clickNext(page)
  await page.getByLabel('Full name *').fill('E2E Patient')
  await page.getByLabel('Mobile number *').fill('09171234567')
  await page.getByLabel('Email optional').fill('e2e@example.com')
  await page.getByRole('checkbox').check()
  await clickNext(page)
  await expect(page.getByRole('heading', { name: 'Review your request' })).toBeVisible()
  await page.getByRole('button', { name: /Request Appointment/ }).click()
  await expect(page.getByText('Appointment request received.')).toBeVisible()

  const admin = await page.context().newPage()
  await admin.goto('http://localhost:3001/login')
  await admin.getByLabel('Email').fill('local-staff@example.com')
  await admin.getByLabel('Password').fill('local-only')
  await admin.getByRole('button', { name: /Sign in/ }).click()
  await expect(admin).toHaveURL(/dashboard/)
  await expect(admin.getByText('Needs your review')).toBeVisible()
  await expect(admin.getByText('E2E Patient')).toBeVisible()
  await admin.getByRole('button', { name: 'Confirm' }).first().click()
  await expect(admin.getByText(/Appointment updated/)).toBeVisible()
})

test('public site renders usable desktop and mobile navigation', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Dental care, thoughtfully done.' })).toBeVisible()
  const width = page.viewportSize()?.width || 1280
  if (width < 600) {
    await expect(page.getByRole('link', { name: /Book a visit/ })).toBeVisible()
    await expect(page.getByRole('link', { name: /Find a branch/ })).toBeVisible()
    await page.getByRole('button', { name: 'Open menu' }).click()
    await expect(page.getByRole('link', { name: 'Our Clinic' }).last()).toBeVisible()
    await page.goto('/book?branch=valley-1')
    await expect(page.getByText('Step 01 of 05')).toBeVisible()
    await expect(page.locator('.mobile-action-bar-booking')).toBeHidden()
  } else {
    await expect(page.getByRole('navigation', { name: 'Primary navigation' })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Locations' }).first()).toBeVisible()
  }
})

test('admin can toggle password visibility, collapse navigation, and export filtered reports', async ({ page, browserName, request }) => {
  test.skip(browserName !== 'chromium', 'The admin controls are verified once in Chromium.')
  await request.post('http://localhost:3001/api/test/reset', { headers: { 'x-mab-test-reset': 'local-only' } })
  await page.goto('http://localhost:3001/login')
  await page.getByLabel('Email').fill('local-staff@example.com')
  const password = page.getByLabel('Password')
  await password.fill('local-only')
  await expect(password).toHaveAttribute('type', 'password')
  await page.getByRole('button', { name: 'Show' }).click()
  await expect(password).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Hide' }).click()
  await expect(password).toHaveAttribute('type', 'password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/dashboard/)
  await page.getByRole('button', { name: 'Minimize navigation' }).click()
  await expect(page.getByRole('button', { name: 'Expand navigation' })).toBeVisible()
  await page.goto('http://localhost:3001/reports')
  await expect(page.getByRole('heading', { name: 'Operational reporting.' })).toBeVisible()
  await page.locator('select').nth(0).selectOption('7')
  await page.locator('select').nth(1).selectOption('11111111-1111-4111-8111-111111111111')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Excel' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^mab-dental-report-\d{4}-\d{2}-\d{2}\.xls$/)
})

test('admin mobile navigation keeps core work one tap away', async ({ page }) => {
  test.skip((page.viewportSize()?.width || 1280) >= 600, 'The mobile navigation is verified in the phone-sized project.')
  await page.goto('http://localhost:3001/login')
  const email = page.locator('input[type="email"]')
  const password = page.locator('input[type="password"]')
  await email.click()
  await email.pressSequentially('local-staff@example.com')
  await password.click()
  await password.pressSequentially('local-only')
  await expect(email).toHaveValue('local-staff@example.com')
  await expect(password).toHaveValue('local-only')
  await page.getByRole('button', { name: /Sign in/ }).click()
  await expect(page).toHaveURL(/dashboard/)
  const mobileNav = page.getByRole('navigation', { name: 'Mobile primary navigation' })
  await expect(mobileNav).toBeVisible()
  for (const label of ['Dashboard', 'Appointments', 'Calendar', 'Patients', 'More']) await expect(mobileNav.getByRole(label === 'More' ? 'button' : 'link', { name: label })).toBeVisible()
  await mobileNav.getByRole('button', { name: 'More' }).click()
  await expect(page.getByRole('link', { name: 'Services' })).toBeVisible()
})
